#ifndef GLOBAL_VAR_REMOTE_H_
#define GLOBAL_VAR_REMOTE_H_

extern _u16 STREAM_FRAME_COUNTER;
extern _u16 MOTION_FRAME_COUNTER;
extern _u16 BODY_CONFIG_FRAME_COUNTER;
extern _u16 SENSOR_DATA_FRAME_COUNTER;
extern _u16 LISTEN_COUNTER;
extern _u16 FIND_ROBOT_COUNTER;

extern _u8 STREAM_FRAME_COUNTER_EN;
extern _u8 MOTION_FRAME_COUNTER_EN;
extern _u8 BODY_CONFIG_FRAME_COUNTER_EN;
extern _u8 SENSOR_DATA_FRAME_COUNTER_EN;
extern _u8 LISTEN_COUNTER_EN;
extern _u8 FIND_ROBOT_COUNTER_EN;
extern _u16 Coordinate_x;
extern _u16 Coordinate_z;

#endif
