#include "simplelink.h"
#include "Global_Var_Remote.h"

_u16 STREAM_FRAME_COUNTER = 0;
_u16 MOTION_FRAME_COUNTER = 0;
_u16 BODY_CONFIG_FRAME_COUNTER = 0;
_u16 SENSOR_DATA_FRAME_COUNTER = 0;
_u16 LISTEN_COUNTER = 0;
_u16 FIND_ROBOT_COUNTER = 0;

_u8 STREAM_FRAME_COUNTER_EN = 0;
_u8 MOTION_FRAME_COUNTER_EN = 0;
_u8 BODY_CONFIG_FRAME_COUNTER_EN = 0;
_u8 SENSOR_DATA_FRAME_COUNTER_EN = 0;
_u8 LISTEN_COUNTER_EN = 0;
_u8 FIND_ROBOT_COUNTER_EN = 0;
_u16 Coordinate_x = 0;
_u16 Coordinate_z = 0;
